### ISSUE TITLE
Crash due to TransactionTooLargeException when sending notification

### ISSUE THREAD

**Issue by H3XDaemon** [adolfintel/OpenPods#169]
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: OnePlus
[Device Model]: IN2015
[Display]: IN2015_11_F.62
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_TW_#Hant
[Process ID]: 28986
[CPU ABI]: none
[Package Name]: com.dosse.airpods
[Version Name]: 1.9.1
[Version Code]: 22
[Error Type]: JVM
[Crash Time]: 2023-07-16T11:46:44.178
[Stack Trace]:
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2090028 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:681)
	at android.app.NotificationManager.notify(NotificationManager.java:628)
	at android.app.NotificationManager.notify(NotificationManager.java:604)
	at t0.b.run(SourceFile:664)
Caused by: android.os.TransactionTooLargeException: data parcel size 2090028 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:672)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3031)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:678)
	... 3 more

**Comment by Electric1447** [comment]
What model of device and os do you use,?

**Comment by H3XDaemon** [comment]
Oneplus 8 with OxygenOS13
