### ISSUE TITLE
App Crash after location toggle

### ISSUE THREAD

**Issue by Domi04151309** [adolfintel/OpenPods#47]
### Description
The app crashes when the location is turned on after being turned off for a long time.
### Log
```
FATAL EXCEPTION: Thread-3
Process: com.dosse.airpods, PID: 19638
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3312968 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:503)
	at android.app.NotificationManager.notify(NotificationManager.java:450)
	at android.app.NotificationManager.notify(NotificationManager.java:426)
	at com.dosse.airpods.PodsService$NotificationThread.run(PodsService.java:332)
Caused by: android.os.TransactionTooLargeException: data parcel size 3312968 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:547)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2962)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:500)
	... 3 more
```

**Comment by Domi04151309** [comment]
[PodsService.java:332](https://github.com/adolfintel/OpenPods/blob/master/OpenPods/app/src/main/java/com/dosse/airpods/PodsService.java#L332)

**Comment by adolfintel** [comment]
I can't replicate this on my phone. How long does it take? And what can you tell me about your device?

**Comment by Domi04151309** [comment]
My device is a OnePlus 6T running Android 10. It happens from time to time but I cannot reproduce it on purpose and I am unable to provide further information about it.
It seemed to happen randomly after connecting the AirPods, turning on the location, turning off the location, watching YouTube for about half an hour and then turning on the location again.
Everything works fine after restarting the app but the "location disabled" stays until the app is restarted.

**Comment by adolfintel** [comment]
Let me know if it happens again
